kind: RoleBinding 
apiVersion: rbac.authorization.k8s.io/v1
metadata: 
  name: mynamespace-user-view 
  namespace: mynamespace 
subjects: 
- kind: ServiceAccount 
  name: mynamespace-user 
  namespace: mynamespace 
roleRef: 
  apiGroup: rbac.authorization.k8s.io 
  kind: Role 
  name: mynamespace-user-full-access
