Installing Prometheus Pushgateway
Introduction
The Prometheus pull model provides a highly resilient method for gathering metrics. However, there are a few cases where this model is not a good fit. Prometheus Pushgateway serves as a middleman, providing a push-based method for gathering metrics without compromising the simplicity of Prometheus server. In this lab, you will have the opportunity to install and configure your own Prometheus Pushgateway instance. This will give you some hands-on experience with the process of setting up Pushgateway.

Solution
Log in to the Prometheus server using the credentials provided:

ssh cloud_user@<PROMETHEUS_SERVER_PUBLIC_IP>
Install and Run Pushgateway
Create a user and group for Pushgateway:

sudo useradd -M -r -s /bin/false pushgateway
Download the archive that contains the Pushgateway binary:

wget https://github.com/prometheus/pushgateway/releases/download/v1.2.0/pushgateway-1.2.0.linux-amd64.tar.gz
Extract the file:

tar xvfz pushgateway-1.2.0.linux-amd64.tar.gz
Copy it to /usr/local/bin/:

sudo cp pushgateway-1.2.0.linux-amd64/pushgateway /usr/local/bin/
Set ownership on the file:

sudo chown pushgateway:pushgateway /usr/local/bin/pushgateway
Create a systemd unit file for Pushgateway:

sudo vi /etc/systemd/system/pushgateway.service
Add the following to the file:

[Unit]
Description=Prometheus Pushgateway
Wants=network-online.target
After=network-online.target

[Service]
User=pushgateway
Group=pushgateway
Type=simple
ExecStart=/usr/local/bin/pushgateway

[Install]
WantedBy=multi-user.target
Save and exit the file by pressing Escape followed by :wq.

Start and enable the pushgateway service:

sudo systemctl enable pushgateway
sudo systemctl start pushgateway
Verify the service is running:

sudo systemctl status pushgateway
We should see it as an active (running) status.

Verify it's serving metrics:

curl localhost:9091/metrics
We should see data returned.

Configure Pushgateway as a Scrape Target for Prometheus Server
Edit the Prometheus config:

sudo vi /etc/prometheus/prometheus.yml
Under the scrape_configs section, add a scrape configuration for Pushgateway. Be sure to set honor_labels: true:

- job_name: 'Pushgateway'
  honor_labels: true
  static_configs:
  - targets: ['localhost:9091']
Restart Prometheus to load the new configuration:

sudo systemctl restart prometheus
Access the expression browser in a web browser at http://<PROMETHEUS_SERVER_PUBLIC_IP>:9090.

Run a query to view some Pushgateway metric data:

pushgateway_build_info
We should see some data returned.